FROM debian:stretch

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y --no-install-recommends sudo cmake curl cmake gcc g++ git libmagic-dev libssl-dev pkg-config ca-certificates binutils gcc libc6-dev libmagic1
RUN apt-get clean
